### ISSUE TITLE
Folding does not automatically restart after quitting Folding at Home process

### ISSUE THREAD

**Issue by cameronlyman** [FoldingAtHome/fah-web-client-bastet#101]
Replication steps were done on Windows 10 Home 22H2.

To replicate, while a machine is folding, quit Folding at Home by right clicking the FAH icon in the bottom right then clicking quit. When you start back up FAH, the folding job will be listed as waiting for resources. Clicking "Pause Folding" then "Resume Folding" fixes the issue.

**Comment by kbernhagen** [comment]
Was this with the client set to `Finishing` when you quit?

If so, that would be a known issue.
https://github.com/FoldingAtHome/fah-client-bastet/issues/89

**Comment by cameronlyman** [comment]
The client was not set to Finishing when I quit.

**Comment by cameronlyman** [comment]
> What version of fah?

v8.1.18

**Comment by jcoffland** [comment]
Should be fixed in v8.3.x
