### ISSUE TITLE
Crash (Access violation) in Windows seemingly related to DNS failures.

### ISSUE THREAD

**Issue by zincan-images** [FoldingAtHome/fah-web-client-bastet#107]
I’ve got error with same issue cause by DNS.

Windows 11 Pro for Workstation 22H2 OS build 22621.2428
Folding @ Home v8.1.18
Edge v119.0.2155.44(Official build) (64bit)

Sometime FAH crashed and then stoped work.
I found error from Event Viewer.
Seems like same type error cause by network  cannot reached to servers.

This issues, I need reinstall work every time.

I uploaded Event viewer log files and screenshot images on Google Drive.

documents
https://drive.google.com/drive/folders/1gThNTdFTKKMyn9z3GYb25EGKKcLumdOl?usp=drive_link

images
https://drive.google.com/drive/folders/17gphJCs_tDEO-P0TTIpN7zvIDwn00TlC?usp=drive_link

Thank you.

**Comment by jcoffland** [comment]
I have not see this before.  It seems that your system failing to respond normally to DNS lookups is causing the client to crash with 0xc0000005 (access violation).

**Comment by zincan-images** [comment]
I'll check with network. (Recently I got error Wireless connection)
Thanks for your reply.
