### ISSUE TITLE
TypeError in current, cannot convert undefined to object in machine.js

### ISSUE THREAD

**Issue by jackschmidt** [FoldingAtHome/fah-web-client-bastet#109]
When running the current pre-alpha 8.3 with 8.2.4 clients, one gets a rethrown error: `TypeError: can't convert undefined to object` from line [107 of src/machine.js](https://github.com/FoldingAtHome/fah-web-client-bastet/blob/ba2ded4b08018f6e0547d16f3f65b773f30f0fb2/src/machine.js#L107). The debugger console led me to think `"scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core"` was relevant, but I think it is not.

The following change allows 8.2 clients to run without trouble:

```
diff --git a/src/machine.js b/src/machine.js
index 6b7345b..244bb32 100644
--- a/src/machine.js
+++ b/src/machine.js
@@ -104,7 +104,7 @@ class Machine {
   get_url(path) {return this.get_id() + path}
   get_info()    {return this.get_data().info || {}}
   get_version() {return this.get_info().version}
-  get_groups()  {return Object.keys(this.get_data().groups)}
+  get_groups()  {return this.get_data().groups ? Object.keys(this.get_data().groups) : [null] }
 
```

I tried ` get_groups()  {return Object.keys(this.get_data().groups||{})}` similarly to `get_info`, but then no machine will display its progress.  It looks like supporting resource groups is handled in the rest of the app (MachineView.vue for example) by get_groups having only a single entry which is falsey.

I'm not sure the folding control works, but I didn't experiment too much with real work units.

Let me know if you'd like a pull request (but that single line change fixes it for me in `npm run dev`)

Thanks for all the hard work! I like the tabs for awards, projects, and news, and I really like the simple display for the points per day.

**Comment by jcoffland** [comment]
I wonder if this works as well:

```javascript
get_groups()  {return Object.keys(this.get_data().groups || {'':{}})}
```

The default group has an empty string for it's name.  The above reproduces that.  I'm a little wary of your solution because I don't know why it works.  Likely there is more to be done to support v8.2.4 clients.  It's not worth a big effort because v8.2.4 clients should not be kept around much longer.

**Comment by jackschmidt** [comment]
I tried your simpler fix, but at first it did not work for me. It looks like it should work, but there is one more problem in the call to UnitView from MachineView:

```
        UnitView(v-if="unit.group == group", :unit="unit", :mach="mach")
```

I think unit.group is null and while both null and '' are false, null != '', so the units are skipped. I added a `|| (!unit.group && !group)` to match the `group = ''` default arguments in src/machine.js which also worked for me with your simpler patch to machine.js line 107.

```
--- a/src/MachineView.vue
+++ b/src/MachineView.vue
@@ -116,7 +116,7 @@ export default {
             title="Pause folding in this group.", :disabled="!connected")
 
       template(v-for="unit in mach")
-        UnitView(v-if="unit.group == group", :unit="unit", :mach="mach")
+        UnitView(v-if="unit.group == group || (!unit.group && !group)", :unit="unit", :mach="mach")
 
   .no-data(v-if="mach.is_empty()")
     p No work units.
diff --git a/src/machine.js b/src/machine.js
index 6b7345b..76de3c0 100644
--- a/src/machine.js
+++ b/src/machine.js
@@ -104,7 +104,7 @@ class Machine {
   get_url(path) {return this.get_id() + path}
   get_info()    {return this.get_data().info || {}}
   get_version() {return this.get_info().version}
-  get_groups()  {return Object.keys(this.get_data().groups)}
+  get_groups()  {return Object.keys(this.get_data().groups || {'':{}})}
 
 
   get_group(name = '') {

```

---

I agree 8.2.4 is low priority and I can just `npm run dev` my patched copy during the migration.

For upgrading, I usually try to wait until all work units are finished, then copy client.db into a new directory and run the new client. Is that too cautious? Can we just run 8.3 in the same directory as 8.2 was run? (same client.db and config.xml). Are work units safe to pause and then start up again with the new client?

**Comment by jcoffland** [comment]
I added a version of your change.

**Comment by jackschmidt** [comment]
Thank you! I still need the change to MachineView.vue to see the work units, but this fixes the error message.

```
--- a/src/MachineView.vue
+++ b/src/MachineView.vue
@@ -116,7 +116,7 @@ export default {
             title="Pause folding in this group.", :disabled="!connected")
 
       template(v-for="unit in mach")
-        UnitView(v-if="unit.group == group", :unit="unit", :mach="mach")
+        UnitView(v-if="unit.group == group || (!unit.group && !group)", :unit="unit", :mach="mach")
 
   .no-data(v-if="mach.is_empty()")
     p No work units.
```

Thanks for fixing disconnected in dark mode!
