### ISSUE TITLE
ETA time display: Reduce character length changes

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#110]
In FAH v8.3.0 from source, on Mint21.1 (Ubuntu 22.04), the ETA time values are shifting around the table display column widths a few times a minute. It's a bit distracting. Please left-pad the seconds with a 0, and right-pad with a space for '1 sec' (this could be done for minutes as well, but seconds are the most noticeable).
Or, have the web page always left-pad the text with spaces to a minimum fixed length.
Or, make that ETA table column have a minimum width to reduce the amount of resizing it does.
And/Or, swap the PPD and ETA columns to help reduce this issue.

![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/b797a681-ac49-418a-bb87-abeddda6d366)

**Comment by kbernhagen** [comment]
Could also reduce this issue by only including seconds when ETA is less than one minute. (client issue)

**Comment by Hou5e** [comment]
That still wouldn't fix the underlying problem of everything shifting around because the text changed from 1-2 digit numbers or the units going singular and plural (adding the 's'). It sounds like the text is in the underlying library, where leaving alone and making that column in the table a fixed-width that would accommodate the largest text string: 20 hours 20 mins (both: ## and plural) would be an easy solution.

**Comment by Hou5e** [comment]
With FAH v8.4.1, this would be finished if a fixed width font was being used. The seconds displayed change the cell width as the number text-width changes ("1" being noticeably thinner than the other numbers).
![image](https://github.com/user-attachments/assets/cba13fb3-8a85-4431-95af-61ba52e44bee)

**Comment by jcoffland** [comment]
Done.
