### ISSUE TITLE
Update the WU Project Number link to show the newer info available

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#111]
In FAH v8.3.0 from source, the 'project' number web link for a WU opens up a new tab in your browser. It would most likely be better to link to the newer WU Details page (using the same link as the button):
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/85a1f743-8345-4930-b2b3-c6719d818f07)
Or, if that is not possible, then less desirably link to the Projects tab/page: https://alpha.foldingathome.org/projects

I do like how the mouse-over the Project Link shows the Run/Clone/Gen info:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/74a9a702-e3b1-41ca-a5c7-3257a1d3b7a8)

**Comment by jcoffland** [comment]
fixed.
