### ISSUE TITLE
Compact the Machines web page layout

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#113]
In FAH v8.3.0 from source, can the message for Disconnected PCs be reduced to one line? So more PCs are visible:
```
No work units.

Start folding to download work units.
```
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/74526f26-8cad-43ac-897c-a87d42b06d43)

**Comment by jcoffland** [comment]
done.
