### ISSUE TITLE
3D Viewer works on the second try

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#114]
In FAH v8.3.0 from source, on Mint21.1 (Ubuntu 22.04), when Folding a WU, it looks like the 3D Viewer launches but with no atoms or frames the first time. Launching the 3D Viewer a second time displays the atoms like it normally would.

**Comment by jcoffland** [comment]
It takes some time to load the visualization data, especially for remote clients.  Once it is loaded into a browser it will be cached making subsequent loads fast.

**Comment by Hou5e** [comment]
Remote clients don't seem to work for me. I'm loading the local GPU WU data in a Firefox browser, and normally it's loaded in less than a few seconds. I waited for the atoms to show up for over 5 minutes a few times, and there were still no atoms... It happens more likely with the (2) GPU PCs, but I think that is just from having 2 chances to see it happen (one for each WU). With the latest debug build on Linux, it doesn't show any errors in the log (the first GPU WU displayed, and the second GPU WU didn't display):
```
[92m10:31:09:D3:msg: {"frame": 0, "cmd": "viz", "time": "2023-12-30T10:31:09.264Z"}[0m
[92m10:31:20:D3:msg: {"unit": "TZ4mjlQbuSTtGnfjEvo3IXHCNSkC2TNXc1VEOSwnQiU", "frame": 0, "cmd": "viz", "time": "2023-12-30T10:31:20.076Z"}[0m
[92m10:31:28:D3:msg: {"frame": 0, "cmd": "viz", "time": "2023-12-30T10:31:27.991Z"}[0m
[92m10:31:32:D3:msg: {"unit": "hVZz7xP5pciShYbxiODIMPeYorVU8zOU6SYYdw-G14o", "frame": 0, "cmd": "viz", "time": "2023-12-30T10:31:32.741Z"}[0m
```
Different PC (Same: first had atoms, second didn't [even after a minute])
```
[92m11:45:14:D3:msg: {"unit": "0zSMUHg1kP5pYh45aml3Whhje783xnM40XlBEldYhAE", "frame": 16, "cmd": "viz", "time": "2023-12-30T11:45:14.069Z"}[0m
[92m11:45:16:D3:msg: {"frame": 0, "cmd": "viz", "time": "2023-12-30T11:45:16.598Z"}[0m
[92m11:45:20:D3:msg: {"unit": "CeDO6Mvepk8l9FSIr0xOmKlYe1iJTkAYhKSPkap7-II", "frame": 0, "cmd": "viz", "time": "2023-12-30T11:45:19.830Z"}[0m
11:45:36:I1:WU2516:Completed 3950000 out of 5000000 steps (79%)
11:45:47:I1:WU2517:Completed 850000 out of 5000000 steps (17%)
[92m11:46:26:D3:msg: {"frame": 0, "cmd": "viz", "time": "2023-12-30T11:46:26.303Z"}[0m
```
I tried a different browser, Chrome on Linux and it happened on the first WU of 2 GPU WUs:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/95569e3c-e47a-4259-b8bb-63c624189cc7)

If you hit the F5 key to refresh, then the atoms show up (Just like closing and reopening the visualization page).

The URL looked correct for either atoms shown or not.

For reproducing it, it seems like if you see the atoms, then you need to wait for the next WU to have a chance at not seeing them.
(like something is not getting reset or initialized between WUs)

**Comment by jcoffland** [comment]
Are you sure a frame as been produced?  The WU has to run for awhile before any frames are available.  In your picture it says "Frame: 0 of 0".

**Comment by Hou5e** [comment]
Yes. That's what it looks like when this issue happens.
If you hit F5, or go back and click the 3D Viewer button again, then all the frames and atoms load correctly.

**Comment by jcoffland** [comment]
This should be fixed now.

**Comment by Hou5e** [comment]
Yes, it's working better now.
I haven't been able to reproduce it with: the latest Windows (Debug) builder file 116, or Linux Debug file 16, using Firefox.
