### ISSUE TITLE
Add a compact theme

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#118]
Can the vertical cell padding be reduced?

This image [without any web browser zoom] requires a 4k monitor to view the entire list of remote PCs when logged in. My setup has some unused RGs that could be deleted (I'm leaving them for testing purposes), but it looks like there's a fair amount of Top and Bottom cell padding that could be reduced or removed from the tables:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/0bacca4a-6a5c-4e49-8506-5e25feb40149)

**Comment by jcoffland** [comment]
There is benefit to white-space.  I suggest we need a "compact" theme.  See #64

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.
