### ISSUE TITLE
Add Web Control Settings page

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#121]
An AppSettings.vue `/settings` would be a good place for

- a direct connect Machines list #61
- theme editing #64
- setting visibility of disconnected/never connected machines #120
- selecting Units table columns shown and order
- build info like version and build date

**Comment by jcoffland** [comment]
I recently added build info to machine details view.

New issue: #128.

The reset are already issues so closing.
