### ISSUE TITLE
Use tabs for groups in Settings

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#123]
Use tabs for groups in Settings.

If layout is wide, use tabs for groups instead of pull down control.

This would give an overview at a glance, and allow one-click selection.

Maybe move delete button down into group area.

@muziqaz

**Comment by muziqaz** [comment]
Again, modern computers have comically massive amounts of space horizontally. 4:3 aspect ratio died long time ago.

**Comment by kbernhagen** [comment]
But not everyone or everything has super wide screens. 

My main display is 1280x720, for vision reasons.

My phone in portrait is very narrow. 

Anyway, web control already has at least two layout widths.

**Comment by jcoffland** [comment]
I planned to do this.  The selection box was a quick hack.
