### ISSUE TITLE
Add per-WU log button 

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#125]
Show log with appropriate filter for selected WU.

**Comment by kbernhagen** [comment]
@muziqaz

**Comment by muziqaz** [comment]
Per Slot aka Resource Group

**Comment by kbernhagen** [comment]
That may require changes to logging. The group is not given on every log line. I can’t seem do “or” searches for multiple WU numbers either.

**Comment by muziqaz** [comment]
I was thinking, maybe the current log "tab" could have a filtering system, similar how it is possible to filter warnings and errors. So maybe add options to filter per slot and per WU, instead of adding separate logging option in UI

**Comment by kbernhagen** [comment]
There is still only one log. Filtering on group will require more info in the log lines.

For example, log lines made by a unit will need to also print the group name.

**Comment by muziqaz** [comment]
For debugging purposes we definitely need logs physically separated by WU at least.

**Comment by kbernhagen** [comment]
For that I think the client would have to make the core logs available separately.

**Comment by kbernhagen** [comment]
I believe it all gets interleaved currently.

**Comment by kbernhagen** [comment]
I think `Unit::getLogPrefix()` would need to include `:groupname:`

**Comment by jcoffland** [comment]
The WU ID is unique for the client.  So the group prefix should not be needed.

**Comment by jcoffland** [comment]
There are already too many buttons, this could be added with #127.

**Comment by muziqaz** [comment]
#127 is reasonable compromise ;)

**Comment by kbernhagen** [comment]
A resource group can have more than one WU. If there are errors happening, the WU number can change rapidly.

I think the group prefix is still useful.

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.
