### ISSUE TITLE
Failure to load ``causes`` from API fails silently.

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#126]
Currently, if the api server cannot be reached, the causes list will be empty in Settings.

Web Control should cache the valid causes list, and have a built in fallback list.

**Comment by jcoffland** [comment]
If the API server cannot be reached then you cannot login so this is moot.  Causes are already cached.

There is currently a problem where if you make too many requests to the API your IP gets blocked for some period of time and all API requests fail.  Reloading Web Control a few times with the developer console open can trigger this.  I need to relax the restrictions a bit.  Note, that having the developer console open can cause the browser to ignore the cache.

**Comment by kbernhagen** [comment]
If you are not logged in, then you are still able to modify the local machine.

This happened recently when the api server was seemingly down. Not just me or some rare limit.

**Comment by jcoffland** [comment]
True

**Comment by jcoffland** [comment]
Now shows an error when causes fail to load.
