### ISSUE TITLE
Feature request: show news items related to the work the user has done

### ISSUE THREAD

**Issue by andrasfuchs** [FoldingAtHome/fah-web-client-bastet#13]
It would be great to read about the results of the work units / projects that my or my team's computer(s) participated in. 

It would personalize the experience more and I think people would share their positive impact proudly with others who could potentially also join FAH.

**Comment by jcoffland** [comment]
We now show the latest F@H news as well as information about the projects being run.  It is unlikely we will show news articles specifically related to the projects being run.  This would require someone to regularly curate the articles.  We don't have anyone who will do that.
