### ISSUE TITLE
Add Project number on the WU information page

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-web-client-bastet#131]
![2024-02-08_200842](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/46302945/21d06c64-efe9-4bc8-bfa3-0a850860cad8)
Would be usefull to have the Protein number between Core and Run/Clone/Generation
To have all the PRCG on the same screenshot. For troubleshooting for example.

**Comment by jcoffland** [comment]
I assume you mean project number.  It is there, it's just below your screenshot and just above the project description.

**Comment by Adanorm** [comment]
I CTRL+F5'ed this time, new URL "beta", I have nothing bellow
![2024-02-09_133537](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/46302945/13bd38fe-bdd2-427e-b15d-539e69641ceb)

**Comment by jcoffland** [comment]
Ah, I see the problem.  The issue is that some projects don't have any project details in the DB and then don't show up.  I'll fix this.  Thanks!

**Comment by jcoffland** [comment]
Fixed.  See https://alpha.foldingathome.org/
