### ISSUE TITLE
Add log of previously completed WUs

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-web-client-bastet#133]

**Comment by jcoffland** [comment]
Screenshot of feature in HFM

![hfm-wu-history](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/1166284/87eae159-c50c-44c3-8531-58e2764834a3)

**Comment by muziqaz** [comment]
A bit more info on the requested feature functionality: per project filtering, as a minimum. HFM user variety of data points possible for filtering, but I think for us as minimum filter per project would be ok.
Either drop down menu or a column on the left (similar to what we see in Benchmark viewer in HFM) would suffice. Only completed/currently running (by monitored/connected clients) projects should be available to see in history viewer

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.
