### ISSUE TITLE
Long usernames cover the rank.

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-web-client-bastet#138]
![rank](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/66015018/694a6000-cf60-40e6-b47a-5e816e951a86)

My username needs to be long to get gridcoins.  I assume there's a rank for me in the same way as there is for curecoin, but it's being covered by my username.  It would be good to shorten it to fit in the display.

**Comment by jcoffland** [comment]
Fixed in upcoming v8.3.5 release.  See https://alpha.foldingathome.org/
