### ISSUE TITLE
Has Battery is incorrect on Windows

### ISSUE THREAD

**Issue by cameronlyman** [FoldingAtHome/fah-web-client-bastet#139]
The "Has Battery" flag is listed as false for my MSI GF65 Thin 10UE when it should be listed as true.

![folding](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20762251/b587b567-76e7-4c38-83d0-2ed0716f1af7)

**Comment by jcoffland** [comment]
This will be fixed in v8.3.5.  Coming soon.
