### ISSUE TITLE
Old PC Account Blocks New PC Account of the Same Name

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#145]
(Similar but slightly different to: https://github.com/FoldingAtHome/fah-client-bastet/issues/216)
I had an SSD stop working, so I replaced it and installed Linux Mint on it with FAH v8.3.5 beta release using the Firefox browser.

After logging-in to my FAH account on the new SSD with the same PC Name, the PC wouldn't show up for remote viewing from other PCs. Where the old account was blocking the new account, it seemed.
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/5657c6e9-292d-4533-a0e3-cfe7794f236b)

I needed to remove both entries in the list for this PC, and re-link it to get it to look like this where it showed up as a remote:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/c9923899-f523-4985-98e6-a8c0b0b20234)

Even though users can fix this issue manually, it might not be obvious for some people.
(I probably could have renamed one of them, but I didn't think of it at the time.)

In this type of situation (duplicate PC name conflict), it might be better to make unique entries (like the PC name with the date added, or Machine Id included, or something like that). Or possibly, replace/update/rename the same named PC account info (this seems less desirable).

**Comment by jcoffland** [comment]
What do you mean by "Blocks New PC Account of the Same Name".  The name is only a display name so I doubt the machines have any effect on each other, other than it being confusing.

Note, if you mouse over the word ``Name`` in the machines list it will show the F@H ID for the machine.  Unless you copy the ``client.db`` file, the client's will have different F@H IDs.

Showing the time the machine was added is a good idea.

**Comment by Hou5e** [comment]
The PC (X99-12, in the Setting's 'Machine' list twice) would be "Disconnected" (and only listed once) when viewing FAH remotes with a web browser on a different PC. Where the original "X99-12" was truly disconnected (doesn't exist anymore), and the new "X99-12" should have had it's status available for viewing (but was not shown because of the old entry was setting the status to "Disconnected", since they were not uniquely named).

I tried to simulate that situation again today, by renaming a Disconnected PC in the Settings Machine list to the same name. It didn't reproduce the issue of: only one of the two same-named PC entries showing up for viewing FAH Remotes (there were both entries). My next guess, would be a full-uninstall and re-install might reproduce that situation, but I haven't tried it.

**Comment by jcoffland** [comment]
I think there may have been confusion caused by #146.  The machines names are only used for display, never internally for deciding where to apply an operation or status update.  However, #146 caused the front end to confuse which machine was which and mix the display names up.

I think this is fixed.  Reopen if you find otherwise.
