### ISSUE TITLE
Allow dots `.` in machine display name

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#147]
Allow dots `.` in machine display name.

Some computers will have one or more dots in the hostname.
An example is the osx build machine.

Web Control considers this an invalid name, and will not link the machine to the account.

https://foldingforum.org/viewtopic.php?t=41221&sid=68e3cb009d0c53bb6df5c78add71336a

An alternative would be for the client to more aggressively sanitize the name.

**Comment by kbernhagen** [comment]
The hover text on an invalid name is also unhelpful.

**Comment by jcoffland** [comment]
This is now supported on https://alpha.foldingathome.org/

**Comment by kbernhagen** [comment]
Is a commit pending?

**Comment by jcoffland** [comment]
no longer

**Comment by kbernhagen** [comment]
Thanks.
Is it possible to get balloon help that indicates what characters are allowed?
Right now, I'm not even seeing the red outline when invalid.
