### ISSUE TITLE
Add an option to manually remove inactive old remote machines

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#154]
![Screenshot_20240609_145459](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/63371529/d532c1fc-9d23-440d-ae1e-2a50a7e0c157)
Is there a plan to add a feature to either hide inactive remote machines from web viewer, or if not, maybe add an option to remove them manually?

**Comment by kbernhagen** [comment]
You can manually unlink old machines from the account settings page. 

There is an issue for hiding disconnected machines.

**Comment by muziqaz** [comment]
> You can manually unlink old machines from the account settings page.
> 
> There is an issue for hiding disconnected machines. #120

Oh, I didn't think to go into account settings.
I take it that if I unlink the machine and later have the same machine start folding, there won't be an issue re-adding it?

**Comment by kbernhagen** [comment]
It will be re-added only if you login with web control on the same computer as the unlinked client. Which is exactly the same situation as for a new client.

**Comment by kbernhagen** [comment]
When a client is unlinked, it retains the settings of the account (user, team, ..)

**Comment by muziqaz** [comment]
Seems to have successfully unlinked and disappeared from the main page list.
There is an option to unlink the machine from which I am unlinking, the one which I am on right now? Is that intentional? Sounds like division by zero. Unless this might be an option for people who want to move to different account/email?

**Comment by kbernhagen** [comment]
You can unlink from the same machine, I think. Most people only have one machine, so this needs to work.

**Comment by kbernhagen** [comment]
I also think you need to logout after the unlink, else the next time you open web control, it will be relinked.

**Comment by kbernhagen** [comment]
You should also be able to delete the account, which should cause all machines to unlink.
