### ISSUE TITLE
Error retrieving /user/ stats for donor name with "non standard" characters

### ISSUE THREAD

**Issue by JWhyFR** [FoldingAtHome/fah-web-client-bastet#155]
Hello, 

There seems to be an issue when retrieving stats for username with "exotic" characters 
Even though the account exists and is active, it shows 0 wu / 0 point / 0 client

![24062408040512165218424531](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/54511523/a3532c6b-6b84-498d-9378-68afd9261c54)

I suspect its the same rootcause as for a previous fix on fah-stats-front-end :  https://github.com/FoldingCommunity/fah-stats-front-end/pull/105

Escaping those characters in ${user} with `encodeURIComponent` should fix it here again 
https://github.com/FoldingAtHome/fah-web-client-bastet/blob/1f1ded6d6c1a8cf9417a3d4ac65adf05af96b4ab/src/stats.js#L113

`https://api.foldingathome.org/user/[PcPerfLeMag]_Thor?team=51`  <= ERROR 502 
`https://api.foldingathome.org/user/%5BPcPerfLeMag%5D_Thor?team=51` <= OK !

Thanks.

**Comment by jcoffland** [comment]
This will be fixed in the next release.  Thanks for the report.

**Comment by jcoffland** [comment]
Actually, it's fixed now in v8.3 Web Control.

**Comment by kbernhagen** [comment]
You mean it's fixed in the live Web Control?
I didn't notice a commit for this in the repo.

**Comment by jcoffland** [comment]
https://github.com/FoldingAtHome/fah-web-client-bastet/commit/8cae5a35946a7436f89f60c0574d8d0287b9a4d7
