### ISSUE TITLE
Stats: Query Username + Passkey instead of Username only

### ISSUE THREAD

**Issue by Shaeric** [FoldingAtHome/fah-web-client-bastet#156]
The v8 client stats show the total accumulated points of a username disregarding a passkey.
The v7 client stats distinguish by username + passkey (similar to https://apps.foldingathome.org/bonus).

This caused some problems when I brought in a friend a couple days ago, that was both surprised to see
that apparently their new username + passkey had already earned a couple millions of points and confused
what steps of the registration process they had done wrong.

I validated this behaviour by running a username of mine with two different passkeys I used in the past in both clients.
I didn't find any issue with the keywords passkey,score,point(s) or stats that mentioned this and hope it's not a replicate.

**Comment by jcoffland** [comment]
Fixed.  Thanks!
