### ISSUE TITLE
Add Account Appearance Item for PRCG

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#162]
Add extra Account Settings 'Appearance' items for: PRCG.
In FAH v8.4.1, there is an item for 'Project' and a separate item for 'RCG', which works as-is.

But, it would be nice to have a single item like it was in the past formatted like:
PRCG_Short: 18223 (491, 1, 17)
PRCG_Long: Project:18223 (Run 491, Clone 1, Gen 17)

Where you can copy and paste it to: https://apps.foldingathome.org/wu  (the short format doesn't work, but the long format does)

**Comment by jcoffland** [comment]
It would better to just integrate the functionality of https://apps.foldingathome.org/wu directly into Web Control.

**Comment by jcoffland** [comment]
This could be automatic in the UnitDetailsView

**Comment by jcoffland** [comment]
I have implemented listing logged credits in the WU details view.
