### ISSUE TITLE
Add Account Appearance Item for ETA (without Seconds)

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#164]
Add extra Account Settings 'Appearance' item for: ETA without displaying seconds, or turn off seconds for all the time displays.
This probably seems redundant, but I would want this for the same reason as #110 and #149.
Even though I can just turn off all the things that change the screen too often now in FAH v8.4.1, I would rather see the ETA but just not updating every second.

**Comment by jcoffland** [comment]
This is too much customization.   The ETA only displays seconds when it's nearly done.
