### ISSUE TITLE
Improve 'RCG' display item for inital pre-WU states

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#165]
The newer 'RCG' display item in FAH v8.4.1, looks weird during the initial states when downloading a WU:

![image](https://github.com/user-attachments/assets/648370eb-dcea-4543-8728-e6719f22b37b)
Where "undefined,undefined,undefined" is pretty long, where blank ("") or "???" would probably be better in that state.

**Comment by jcoffland** [comment]
Done
