### ISSUE TITLE
CTRL+C isn't a good keystroke for 'Connect directly to a client'

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#166]
There were many times where I wanted to copy text from the web UI in FAH v8.4.1, where the keystroke CTRL+C brings up the 'Connect directly to a client' dialog on the: Machines page, Log page, Account Settings page (any of the pages). This behavior was unexpected, and a different keystroke should be used for that dialog (or a button somewhere in the UI).

**Comment by kbernhagen** [comment]
No keystroke is good for mobile.
A button would work better.

**Comment by jcoffland** [comment]
I've moved it to the machine settings page.

**Comment by kbernhagen** [comment]
Of course, it cannot be changed when there is no existing direct connection.

**Comment by jcoffland** [comment]
True.  It exists it's just hidden unless it makes a connection.  Maybe we need a double-tap somewhere to unhide it.

The problem is that I want it to work without having to login to your account so it cannot go in account settings.  But I don't really want to add another button for it on the main screen because it's not something most users should worry about.

**Comment by kbernhagen** [comment]
So if a user has a client elsewhere or on a different port, there is no way to point web control at that client. Unless it is also linked to an account.

This was handled fairly transparently by the old default_address() code.

**Comment by kbernhagen** [comment]
The only general solution I can think of is to have a direct clients list panel.

**Comment by kbernhagen** [comment]
Most people will not be changing `allow` or `http-addresses`, so maybe none of this matters much.

**Comment by jcoffland** [comment]
Right, this is really only a niche feature.

**Comment by kbernhagen** [comment]
The direct address field is very brittle.
If left off, the default port is not added.
It seems I cannot use `localhost` or other named hosts.

**Comment by jcoffland** [comment]
I've moved this back to a hotkey.  This time CTRL+SHIFT+L.  I don't think it is necessary to support this on mobile and I don't like have this option exposed in machine settings.  Users are likely to change it and end up with a broken client.

I also added some input validation.  This does not prevent all possible bad inputs.
