### ISSUE TITLE
Recent WU History didn't get status after the log rotate

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#168]
For FAH v8.4.1 in Firefox viewing remotes, WU8814 didn't update the Recent WU History after the Log Rotation (as far as I can tell from the image)

![image](https://github.com/user-attachments/assets/06d3bdf5-f27c-43f8-afc6-9b99e572b90a)

After a refresh without cache, a few hours later:
![image](https://github.com/user-attachments/assets/3f38808b-9779-4b19-96ab-83c4e6b82984)

Log before rotate (not that useful): WU8814 before rotate: [log-20240724-000000.txt](https://github.com/user-attachments/files/16356175/log-20240724-000000.txt)
Log after rotate (not that useful): WU8814 --> WU8817: [log-20240724-0156.txt](https://github.com/user-attachments/files/16356091/log-20240724-0156.txt)

This issue most likely lost connection and then didn't update / fix the UI display issue later.

**Comment by jcoffland** [comment]
Should be fixed in v8.4.2
