### ISSUE TITLE
Work Unit Averages, Run Time in FAH v8.4.1

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#169]
1. For FAH v8.4.1 in Firefox viewing remotes on Windows, in the WU Averages, it looks like the 'Run Time' is a summation and not an average like the table title says (high WU Run Rate = higher Run Times). I'm not sure which you wanted: Average Run Time or Total Run Time (or both?).

2. 'Work Unit Averages': It looks like it only displays completed in the last day (or assigned in the last day?), where changing the day or using a date range would be useful in the future.

3. The double scrollbars look odd, but I'm sure no one really cares as long as they can scroll to see the displayed info.

4. It would be nice to have some more informational comments for what you're looking at (like the Account Settings page).
Having it labeled for #160 would also make it more clear to see: that this info is per PC (or per PC RG?) and not aggregated for all PCs per WU 'Project' number like you would initially guess (until you see multiple 'Project' numbers listed).

(The 0 PPD entries were WUs from the older FAH v8.3.17 clients before updating them)

![image](https://github.com/user-attachments/assets/16c85d5e-7e3e-4408-b617-e8312c058bf6)

---
Later in the same day:
![image](https://github.com/user-attachments/assets/f43f8ffe-24ef-4b82-8f0f-b79fc30a8596)

**Comment by muziqaz** [comment]
PPD entries in Averages seem to be inconsistent to show up. On mine all of them are showing 0.

**Comment by jcoffland** [comment]
v8.4.2 addresses most of the issues here.
