### ISSUE TITLE
Add extra TPF column for average of fastest 3 frame (excluding some odd extremes)

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#170]
Could we get an extra data value in Work Units section for fastest TPF?
Currently main page and Work Units section are displaying (from what I understand) overall average with some dark magic mixed in.
Log is showing TPF of 2m3s, yet main page and Work Units are showing 2m27s. (Not sure that my understanding was correct in above sentence).
Only time I see 2m28s in the log is every 5%, when checkpoint is being written, and since the project is like 1.something million atoms, checkpoints add 20+s to every 5th frame. Since checkpoints (while they influece overall WU value upon completion), don't represent compute part of the simulation, when we benchmark the projects, we need pure TPF value to determine the BC and PPD value.
HFM showed several TPF values (current, fastest, average, etc). I think for a moment all we need is fastest (which would be best determined by 3 fastest TPFs. If possible, maybe implement a failsafe that among these 3 fastest TPFs, there is no extreme cases, like computer clock skew, or pause/resume time.

Thanks

**Comment by muziqaz** [comment]
I can see that TPF slowly is ticking down frame by frame. At 23% it is now showing 2m 14s. It would be helpful to get more precise TPF values in main page from the start of the WU.
I'll attach few screenshots for reference:
![250](https://github.com/user-attachments/assets/1f228180-9e85-4ab2-b7a5-0865816255c8)
![250a](https://github.com/user-attachments/assets/f7b76cd7-14d4-4613-9bc2-c0106dfb82bb)
![250b](https://github.com/user-attachments/assets/8e3c0630-6369-4cba-96f2-79aa0c6d2225)
![250c](https://github.com/user-attachments/assets/8eb1d1d1-bd68-4999-9ef9-715ae22160ca)

**Comment by jcoffland** [comment]
I believe this is sufficiently covered by the new WU filtering features which computes average, min and max TPF for the selected WUs.  It does not exclude any extreme values but you could potentially exclude them via the filters.
