### ISSUE TITLE
Web client not finding Windows host?

### ISSUE THREAD

**Issue by Wedge009** [FoldingAtHome/fah-web-client-bastet#171]
All but one of my machines currently contributing to Folding@home are Linux-based - the exception is running Windows 7, which I know is no longer supported but I note that [Folding's download page](https://foldingathome.org/start-folding/) cites Windows 7 as the minimum version. (With the old v7 client, I had no trouble reading all hosts via the stand-alone GUI control tool.)

Is there something I might be missing or anything (logs, etc) I can look through to see why the Windows host is being missed? I don't expect it to be relevant, but I'm using Firefox browser in both Windows and Linux. 

The view from the lone Windows machine - of course it can see itself, and it has no trouble seeing the other, Linux-based, hosts (at present I'm only interested in running CPU work):
![image](https://github.com/user-attachments/assets/cb34d0bb-fe08-4a22-a0b9-a7d971c80d8b)

The view from the Linux hosts, which can see each other, but not the lone Windows host:
![image](https://github.com/user-attachments/assets/edfad045-178f-4862-bf7d-13d22fc50b37)

I apologise if this is the wrong place to ask, but I couldn't see a clear category to ask this kind of question in the forums.

**Comment by Wedge009** [comment]
Curiously, just minutes after posting that, the Windows host popped up (nearly a day after adding it to my account). Weird.

**Comment by kbernhagen** [comment]
Windows 7 is supposed to be supported by v8.
