### ISSUE TITLE
Center align column headers on the WUs page

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#173]
For viewing WUs in FAH v8.4.2 (more noticeable in 'Wide View' mode), the 'Info' column header should be center aligned, and not right aligned:
![image](https://github.com/user-attachments/assets/6b4abe87-1fbf-4a90-9971-777e00cc611d)
The WU Averages table above it looks like the 'PPD' column might have the same issue.
I think most all of the column headers on the WUs page would look fine if they were center aligned.

**Comment by jcoffland** [comment]
Thanks.

Right alignment is good for numbers so they line up properly.
