### ISSUE TITLE
Implement an option to see separate completed WUs within the project in "Work Units" section

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#180]
As per discussion here: #177 

Initial comment quote:

> Work Unit Averages will not suffice for us who are benchmarking new projects for public release.
> When project is pushed to internal testing, quite often researcher (for one reason or the other) has WUs set up to certain step length, so in the beginning one frame takes 10s to complete. We try these initial WUs, and make a suggestion to a researcher to increase the WU length, by increasing number of steps within the simulation. Researcher recreates the project under same project number and pushes to us again. We run it, and this time TPF is at 60s. v8 Work Unit Averages records both WUs under same project, so average TPF comes out as 35s, which is incorrect, since we want to ignore initial WUs in our Base Credit suggestions, and would just use 60s TPF WUs for that. HFM allowed us to wipe old WUs from the benchmark section of the app, so that app would record just the newly regenerated project data and calculate avergaes just from them. So, in v8 we would need an option to see individual WUs completed under the project (and be able to remove unwanted WUs), while still be able to see automatically calculated averages.

I'll add this crazy idea of removing Averages section completely as per this [Issue #177 comment](https://github.com/FoldingAtHome/fah-web-client-bastet/issues/177#issuecomment-2296549577)
Plus your own comment about it in this [Issue #177 comment](https://github.com/FoldingAtHome/fah-web-client-bastet/issues/177#issuecomment-2296449573), which kinda supports this idea.

**Comment by jcoffland** [comment]
I believe this is covered by alpha v8.4.4.
