### ISSUE TITLE
Add column for "Failed" or "Successfully Completed" in "Work Units" section

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#181]
As per my comment in #177 
Quote: 

> It would help us (testers) a lot if we could have a column which tells us if the WU has been completed successfully, or if it failed, what was the cause of the failure. Sometimes project runs stable, and suddenly there is one gen or run which is unstable, so with above info, we would be able to point out to researchers that we are seeing certain gens/runs are failing. That also helps with certain hardware failing with certain projects/WUs. That's where being able to see each WU completed under the project would help.

**Comment by muziqaz** [comment]
I would add to this:
Instead of adding new column, why not add another "condition" in `Status` column. At the moment as far as I can see there are only 2 states available in `Status` column: `Running` and `Ended`. `Ended` encompasses successfully finished and also failed WUs. If you add `Failed` as a 3rd state, and give it some sort of red coloured distinct icon, that would be enough, IMO. Though failure cause column would be very helpful, but not really essential.

**Comment by jcoffland** [comment]
v8.4.5 adds WU end states.  You can select successfully completed WUs by selecting the ``CREDITED`` state.

**Comment by muziqaz** [comment]
Does the fix incorporate different icon for failed WUs?

**Comment by jcoffland** [comment]
yes
