### ISSUE TITLE
Add WU number in `Work Units` section

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#183]
![Screenshot_2024-08-20-10-46-33-839_org mozilla firefox](https://github.com/user-attachments/assets/ee8af136-de3f-4bb9-9a1f-a9a5b34da076)

It would be good to have an option to add WU number as a data column in the recent WU history.
So in the screenshot you can see that there is one WU in the project which has very long TPF. If I had WU number of the WU, I would be able to enter it into search/filter bar in log section of the web control, and see if this is fahclient misreporting or if there was something else going on with that WU, and with RCG of that WU, I can report to researcher that this specific run is misbehaving.
This is providing that fahclient saves certain amounts of historic logs, which I believe it does.

**Comment by jcoffland** [comment]
If you click on the info button this information is available.

I did have this in the Work Unit History but I found it confusing because different WUs on different machines may have the same number.  WU number is local to the machine.

**Comment by muziqaz** [comment]
> If you click on the info button this information is available.
> 
> I did have this in the Work Unit History but I found it confusing because different WUs on different machines may have the same number. WU number is local to the machine.

Ah, makes sense
