### ISSUE TITLE
Q: How is the WU history being logged and by what?

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#188]
So, here is a scenario:

3 machines are running v8 with their browsers open on each of the machine. Only 1 machine is remotely monitoring other 2, while also (obviously) monitoring itself. How does the historic WU logging work, and where is the database being saved? Is it on each of the machines, plus the one which is monitoring everything, or each of the machines and monitoring machine just grabs the database info from remote machines, plus its own finished WU history?
Is the fahclient writing in database file or is web control doing that?
Can I close web control on all PCs and monitor everything through the phone, and still have all the WU history saved?

Thanks

**Comment by jcoffland** [comment]
Each machine running the client saves its own WU history to its own database.  The frontend, aka Web Control, aka fah-web-client-bastet, requests this data from the client.  Each client sends information about the most recent 500 WUs plus any currently active WUs when the frontend requests it.  No history is lost by closing Web Control.  Web Control does not need to be monitoring the clients in order for the WU history to be recorded.  HFM probably needs to be connected for the data to be saved.  That's not the case here.

**Comment by muziqaz** [comment]
Thanks, that answers it perfectly
