### ISSUE TITLE
Web Control jumps ungracefully due to Team Logo refresh

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#193]
https://youtu.be/DA18Om2DZw8
Please see the video clip of the event

Now that I added remote client monitoring, Web Control refreshes itself regularly.
This in turn look very ugly, because every refresh is also refreshing Team's logo, which takes a bit longer than other content refresh (since logo is hosted on 3rd party cloud provider), thus the whole UI twitches every 20s or whatever intervals it is refreshing at.

Is it possible to cache Team's logo somehow, that it doesn't spazz out the whole page? Maybe refresh just machine info, and leave Team's section as is, if possible.

As I'm writing this, in the corner of my eye I see these refreshes and it is bothering the hell out of me :D
P.S. (Most important thing) All these refreshes, if they are redownloading Team Logo over and over again, it might blow up the data limits set up with photo storage providers. I know a lot of the "free" photo storage providers have these monthly data limits, which are quite limiting

Thanks

**Comment by muziqaz** [comment]
I just checked it on Android Firefox (monitoring from work), and there are no refreshes at all. No jumping, nothing.
Is this something to do with Mint Linux Firefox, and how it handles things? I'll probably try different browsers on that system to have more data

**Comment by jcoffland** [comment]
If you disallow saving cookies it may cause the client to refresh.

**Comment by jcoffland** [comment]
I'm not totally convinced that's a page refresh.  A page refresh would also likely cause the remotes to reload and come back one at a time.  Something weird is going on though.  It looks like just the header is flashing.

**Comment by muziqaz** [comment]
I have it open right now, and while doing other work I can see the monitor with the corner of my eye, and there is no more twitches. I have not done anything since the time it was spazzing out. No reboots, no browser restarts, nor page reloads. Hopefully it was one off freakout. Will keep monitoring, and update if this shows up again

**Comment by muziqaz** [comment]
Ok, it started again, out of nowhere. This time it is every 1 minute or so, while before it was much more frequent.

**Comment by jcoffland** [comment]
Is there anything interesting in the browser's developer console when this is occurring?

**Comment by muziqaz** [comment]
I'll have to have a look.
Meanwhile I downloaded Vivaldi browser.
There is no twitching on that browser yet (hour or so since launching).

**Comment by jcoffland** [comment]
I cannot reproduce this.

**Comment by muziqaz** [comment]
Yeah, this was very random one. Now that I have all my machines moved to V8, and web control page is full of machines I don't see any jumping. I even tried for couple of machines on the page. Still could not catch it jumping. I will keep monitoring, and if I happen to see it doing this, I will observe the console to see if anything funny is happening. I'll close this issue and if it pops up again and I have proof, I'll reopen it
