### ISSUE TITLE
Work Units section does not show Windows icon by Windows machine WUs

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#194]
![WU History win32](https://github.com/user-attachments/assets/d8160b76-c295-41de-80c1-6ad7a9ea11ca)
Linux penguin shows up, yet Windows machine WUs have no icon.

Also in filtering section in OS drop down it says win32. Would look better if it was called Windows or Win64, and Linux instead of linux (I know I know, nitpicking :D )

**Comment by jcoffland** [comment]
Fixed in v8.4.5
