### ISSUE TITLE
Keep filtering preference in Work Units section until going to another tab

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#198]
So in `Work Units` section if I am inspecting a group of WUs, which I filtered off, when I click on WU `Info`, and then go back to WU list, filters have reset, so I have to apply my filters again to continue inspecting that group of WUs. Now when I go to `Machines` tab, or any other tab outside of `Work Units`, filtering can be reset, it makes sense, since if you leave `Work Units` tab, it is safe to assume I have finished with the filters. Since `Info` for each WU is within `Work Units` tab, it makes sense to keep filters intact.

Thanks

**Comment by jcoffland** [comment]
Fixed in v8.4.5
