### ISSUE TITLE
v8.4.5 WU History showing credited WUs as 0% complete

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#202]
![wu history1](https://github.com/user-attachments/assets/01b84eed-ebd6-4146-ab2e-b1db1c5bf6af)
![wu history2](https://github.com/user-attachments/assets/fb5a3112-2817-4c98-a31e-003bb9ecde43)
As per the screenshots. All WUs have been completed by new v8.4.5.
Some are shoing up as 0% complete, one is showing up yellow as 99.8% complete.
Some are showing 100% complete, but in yellow. Though yellow might be the intended color for credited projects. One screenshot is random WU from the list which is shown by server it has been completed, but WU Info is showing 0%.

**Comment by jcoffland** [comment]
This should be fixed.

**Comment by muziqaz** [comment]
haha, yes, I was just looking for this thread and couldn't find it, to comment that I can now see everything displayed correctly.

Thanks
