### ISSUE TITLE
Retaining historical data from unlinked PC

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#205]
Hi,

I just unlinked one of my PCs from the account because I am moving this PC to new hardware and to Linux, and historical data from that PC is gone when I view WU History from different PC. I probably know why this has happened, and I understand, but is it possible to get some magic going to retain that data within the account, that I could still get back to it for comparisson and check up reasons in case of some other use having issues with their similar harware of my unlinked PC?
This is also useful to see the generational hardware improvements which might impact FAH code, or OS performance differences.

OR, if I do not unlink that PC, that should stay within my account WU history, shouldn't it? It does not :(

**Comment by jcoffland** [comment]
The WU data is not stored with the account.  That would require maintaining a new table in the DB.  This is not going to happen.  If you unlink at client it's WU history will not show up.  If you relink it to the account it should come back.
