### ISSUE TITLE
Stats tab page is blank for about a minute

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#210]
This seems to be because of an exception in StatsView.vue line 42.
JavaScript error:
```
TypeError: this.$adata.teams is not iterable
```

**Comment by kbernhagen** [comment]
This is with team 1971.

Another user first reported the problem.
User [The_HAX0R_31337](https://stats.foldingathome.org/donor/id/717771360)
Team LinusTechTips_Team (223518)

**Comment by jcoffland** [comment]
Should be fixed now on alpha.
