### ISSUE TITLE
Status bars not updating

### ISSUE THREAD

**Issue by jon-ault** [FoldingAtHome/fah-web-client-bastet#216]
8.4.9 running on Windows 11 with Firefox 132.0.2, the status bars are grayed out and showing 0%. This is not happening on my Mac running 8.4.9 with the same Firefox.
![Screenshot 2024-11-21 132642](https://github.com/user-attachments/assets/ebebf77f-76d3-43c9-bf18-d11a6f7d19f0)
![Screenshot 2024-11-21 132713](https://github.com/user-attachments/assets/d2c05140-7b73-4289-a62e-5778046c5a46)

**Comment by muziqaz** [comment]
Are you running some extra security things enabled on Windows or the browser?

**Comment by jon-ault** [comment]
Nevermind, I stupidly forgot to update my bookmark and was still looking at the old "v8-3.foldingathome.org" URL. Once I updated the URL to "v8-4" the bars started working properly.
