### ISSUE TITLE
Entering a Passkey causes failure of WU's and the Stats page to be blank.

### ISSUE THREAD

**Issue by abes200** [FoldingAtHome/fah-web-client-bastet#222]
When I add the passkey and click save, the 'Stats' tab when clicked on brings up a completely blank page with the error: ``TypeError: r.stats.score is undefined`` in the inspector console window. I tried this in Firefox and also in Chrome with the same results. Also I tried completing a couple of WU's while the passkey was active and I noticed an error while mousing over the FAH icon saying some errors occurred and the WU's when finished did not seem to show up on the stats page (after removing the passkey to get the stats page to work).
If I remove or alter the passkey at all (such as removing a single character as it will still accept the 1 char less passkey) then the stats page immediately comes back. Put the passkey in as it was sent to me and the stats page goes blank and the WU's are not credited.
I am using V8.3.18 which is the latest version on the FAH website. I tried uninstalling and re-installing and then entering the passkey again but the problem persists.

**Comment by jcoffland** [comment]
I've made some changes to the v8.4 Web Control can you do a page reload and try it again?

**Comment by jcoffland** [comment]
Also, if you encounter more errors I will need to know at least your F@H user name in order to investigate further.

**Comment by abes200** [comment]
Firstly, yes this seems to be working fine now. In fact it shows that I did complete a couple of WU's with the passkey. Removing the passkey and I can see the WU's I had done without it. I will confirm by doing some more with the passkey put in, but seeing as soon as I put the passkey in the stats page went to a completely blank page and now it shows up just fine I would say it's fixed!

Secondly, I have to say the timing on this was incredible. I actually thought I had just fixed the issue by re-installing it (actually for the 4th time) and I came here to update this post.

I will add though that I am getting these errors show up now in the inspectors console that were not present before on the folding@home client page. Although they do not seem to have any impact on the page itself, and I just started folding now and it's downloaded the projects and they do seem to be progressing as the % complete is going up and the times and PPD are changing accordingly.

"Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
"TypeError: o.sizes.medium is undefined
    get_featured_image https://v8-3.foldingathome.org/assets/index-78d84421.js:3643"

I will add my username: xmqte8p0728h
Could either of these errors be caused on my end by the re-install having a glitch on the way through? It would not be the first time a simple re-install has fixed a problem, or caused one.

**Comment by abes200** [comment]
Firstly, yes this seems to be working fine now. In fact it shows that I did complete a couple of WU's with the passkey. Removing the passkey and I can see the WU's I had done without it. I will confirm by doing some more with the passkey put in, but seeing as soon as I put the passkey in the stats page went to a completely blank page and now it shows up just fine I would say it's fixed!

Secondly, I have to say the timing on this was incredible. I actually thought I had just fixed the issue by re-installing it (actually for the 4th time) and I came here to update this post.

I will add though that I am getting these errors show up now in the inspectors console that were not present before on the folding@home client page. Although they do not seem to have any impact on the page itself, and I just started folding now and it's downloaded the projects and they do seem to be progressing as the % complete is going up and the times and PPD are changing accordingly.

"Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
"TypeError: o.sizes.medium is undefined
    get_featured_image https://v8-3.foldingathome.org/assets/index-78d84421.js:3643"

I will add my username: xmqte8p0728h
Could either of these errors be caused on my end by the re-install having a glitch on the way through? It would not be the first time a simple re-install has fixed a problem, or caused one.

**Comment by muziqaz** [comment]
To OP: please update to latest beta from foldingathome.org/beta

To Joe: I think it is time to get v8.4.9 posted as full release. Dealing with v8.3 problems is getting old now :)

**Comment by abes200** [comment]
No worries. I thought that was the case but wanted to double check just in case. Thanks again!
I have had a look at the 8.4 and downloaded it. Surprising it's so much smaller. Also as a note windows Smart Screen blocks its install as unrecognized app. Run anyway etc, but worth mentioning. Possible some might avoid it.
Appreciate the help and hope you all have a great new year!
