### ISSUE TITLE
"Projects" tab in Web UI is empty

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#223]
![projects](https://github.com/user-attachments/assets/22584d82-1842-4085-bd53-bd4ff29dc3ec)
I cannot remember what it is supposed to show, but for a moment it is saying there is no active projects
This is on the client which is folding right now

**Comment by jcoffland** [comment]
It should show the project info for those projects that are currently running on your machines.  If none of the projects you are running have descriptions in the DB then it might also be empty.

**Comment by muziqaz** [comment]
I was pointed this out by user who is folding full fah, so it is very unlikely they are folding a project without description, especially when we are trying to check all new projects out if they have description or not before they are released. However, you are right, in my case projects which I was folding at this time, have no description yet.
