### ISSUE TITLE
Clicking on the "Pause Folding" button, I selected "Finish up, then pause" however the WU immediately paused

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-web-client-bastet#42]
`15:25:58:I1:WU4:WARNING:Console control signal 1 on PID 5548
15:25:58:I1:WU4:Exiting, please wait. . .
15:25:58:I1:WU4:Folding@home Core Shutdown: INTERRUPTED
15:25:59:I1:WU4:Core returned INTERRUPTED (102)`
Clicking on the "Pause Folding" button, I selected "Finish up, then pause" however the WU immediately paused.  W10-64 22H2

**Comment by kbernhagen** [comment]
This is a fah-client issue, which also occurs on macOS.

**Comment by jcoffland** [comment]
Moving to https://github.com/FoldingAtHome/fah-client-bastet/issues/53
