### ISSUE TITLE
Show  WU TPF

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-web-client-bastet#43]
In order to give researchers Base Credit recommendations, internal testers need access to WU TPF and allow passing --disable-cuda to the core for benchmarking purposes.  Thanks.

**Comment by jcoffland** [comment]
Two issues in one.  Splitting. https://github.com/FoldingAtHome/fah-web-client-bastet/issues/49

**Comment by jcoffland** [comment]
Is TPF the time taken by the last 1% of the WU or an average for the whole run so far?  Is TPF estimated before the first 1% is complete?

**Comment by rhavern** [comment]
I'm fairly sure that TPF in v7 is given as an average for all the frames completed in the current WU.  No accurate estimation is given prior to the first 1%.

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.
