### ISSUE TITLE
FAH v8 Installed as All Users; not using any v7 settings from Current User data location

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#45]
On Windows, FAH v8.1.3 installed as All Users by default, and didn't use any v7 settings from Current User data location.

This will be mildly annoying for existing users upgrading, and can easily be fixed in the NSIS installer code. Where the installer would look in the All Users folder for 'config.xml'. If it's not there, then look for a copy of the 'config.xml' in the default v7 Current Users folder, and copy it to the new All Users location, if it exists.

**Comment by jcoffland** [comment]
Any interest in creating a PR for this?
