### ISSUE TITLE
FAH v8.1.3 on Windows, GPU had a hard time getting work

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#46]
The log file below, has the GPU slot failing to get work on a new Windows install. It had no existing settings, so I paused it, and setup my user info and enabled the GPU. Not sure if this was just bad AS luck, but it seemed like an error, and not what you want new users seeing when their first startup.

```
08:52:47:I1:WU2:Retrying in 8 mins 32 secs
09:01:19:I1:WU2:Downloading WU
09:01:19:I1:OUT18:> POST https://pllwskifah1.mskcc.org/api/assign HTTP/1.1
09:01:19:I3:Connecting to pllwskifah1.mskcc.org:443
09:01:19:E :WU2:Failed response: EOF
09:01:19:I1:WU2:Too many retries, failing WU
```

[log_2022-11-15_01.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10012000/log_2022-11-15_01.txt)

**Comment by jcoffland** [comment]
This would be a backend problem (i.e. fah-client-bastet).  Moving to: https://github.com/FoldingAtHome/fah-client-bastet/issues/52
