### ISSUE TITLE
Allow passing --disable-cuda to core

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-web-client-bastet#49]
Passing --disable-cuda to the core is needed for benchmarking purposes.

Originally reported here: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/43

**Comment by jcoffland** [comment]
Could this be handled by setting an environment variable?  See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars.  Setting ``CUDA_VISIBLE_DEVICES=GPU-00000000`` may work.

**Comment by rhavern** [comment]
Regardless of if that may work, it certainly isn't as convenient as the current v7 methodology.

**Comment by jcoffland** [comment]
Indeed.

I believe the cores ignore options they don't understand so we could add an option to set core arguments for all cores and ``--disable-cuda`` would only affect OpenMM cores.  Mainly, I don't want to clutter the UI with too many configuration options.

**Comment by rhavern** [comment]
I understand wanting to keep the UI clean but I don't want beta testers losing functionality due to the upgrade.  Agree that cores ought to ignore commands they don't understand and matches my experience in v7.

**Comment by jcoffland** [comment]
This is covered by https://github.com/FoldingAtHome/fah-client-bastet/issues/207
