### ISSUE TITLE
Per device control required

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#52]
This was mentioned before in previous versions. This client will go nowhere if there is no "slot"/per device control. Pause only works globally.
Whichever way you look at it, you have to add slots as a concept back. Sometimes it is more beneficial to run 2 CPU slots (with let's say 15 threads used) instead of one 30 thread one. Fahcores simply do not scale well past certain amount of threads. Forcing a user to waste their resources without option to split into smaller thread count slots is counter productive.
A user with 192 cores/ 384 threads might even crash the fahcore/WU as witnessed before with even smaller thread count CPUs. In an era of massive multicore CPUs we will cause more problems rather than solutions

**Comment by Hou5e** [comment]
It seems like the 'Resource Groups' ability, like slots, gives you the granularity you are asking for now:
![image](https://user-images.githubusercontent.com/20870053/210727258-c571a4b3-d474-49b1-8b1e-cafc679cca83.png)
This issue can probably be closed
