### ISSUE TITLE
Show PPD & TPF on WU line

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#55]
In the age of ultra wide monitors we can use full width of the browser and add a lot of useful data regarding the WU the "slot" is folding.
PPD, TPF, what cause is WU behind, etc. Even a small snapshot of the 3d view of the protein could be shown too.

**Comment by kbernhagen** [comment]
Client publishes WU ppd estimate after a while.
Web control just needs to display it.

**Comment by jcoffland** [comment]
See #43 and #18.  I think these cover this feature request.
