### ISSUE TITLE
Saving settings, Firefox browser asks to save password

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#56]
Saving the settings causes the Firefox Browser to prompt you to save your username and password for the website. This is mildly annoying that the browser is picking up the team number and passkey to try and save:

![image](https://user-images.githubusercontent.com/20870053/204279011-463d16f0-1154-414b-939e-1af454a314fd.png)
(I have seen this on Chrome recently with v8.1.11, but I've also seen it not happen with an older version of FAH)

If this behavior is going to remain, then saving the Username and Passkey would be best (instead of team number and passkey).

**Comment by jcoffland** [comment]
Should be fixed in v8.3.2.
