### ISSUE TITLE
Support remote browsers

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#58]
If running on a mobile browser, do not auto add localhost:7396, allow setting host peers only.

This could allow using a phone or tablet browser to access local lan client peers that have been configured to `allow-remote-control`.

Browsers that don't allow insecure content (Safari) would not be supported. This probably includes all browsers that use WebKit.

**Comment by kbernhagen** [comment]
Note that #62 does not address this.
There is still a need for `https://app.foldingathome.org/` to work on mobile.

**Comment by jcoffland** [comment]
This will require us to proxy client monitoring via F@H servers.

**Comment by kbernhagen** [comment]
I think you’re misunderstood. 
the only thing required was to let the client host be set by some means other than Carl-shift-L, which cannot be typed on a phone.

**Comment by kbernhagen** [comment]
I was not asking for Safari support in this issue.

**Comment by kbernhagen** [comment]
All I need for now is to be able to use an unmodified web control vended by client web-root.

**Comment by kbernhagen** [comment]
A button that pops up LocationDialog is sufficient.

**Comment by kbernhagen** [comment]
This is completed as of v8.3.1 or earlier.
