### ISSUE TITLE
Config Settings Resource Usage for GPU, display can say 0 CPU

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#60]
This appears to be cosmetic, and just the UI needs to be updated in this situation to be accurate.
If you select 0 CPU, then enable the GPU, the UI still says 0 CPU and should be updated to 1 CPU in that case.
![image](https://user-images.githubusercontent.com/20870053/209624942-8ccb0f73-24c5-4330-8e4c-bcd3bafaa74a.png)

When you save the settings with 0 CPU and 1 GPU, then reopen the settings, it says the correct amount : 1 CPU and 1GPU. Like:
![image](https://user-images.githubusercontent.com/20870053/209625495-40337c1d-fcda-4d91-b1e5-a5e926b52bc6.png)

**Comment by jcoffland** [comment]
This should be fixed now.
