### ISSUE TITLE
Add hosts list

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#61]
Enhancement request:

Give web control its own list of hosts (remote peers), not including any RGs, in a left-side collapsible column.

The default list would be just `127.0.0.1:7396`.
Store this host list in cookies.

Allow multiple selection in list.
Maybe have an "All Hosts" item.

Load, but do not save, hosts gleaned from client's peers lists.

Tolerate unable to connect to localhost without locking up ui.

On a mobile browser, neither display nor try to connect to localhost in units table.

Support local fah-client vended web control:

If browser origin is not `https://app.foldingathome.org`,
add the origin as an implicit remote host.
E.g., if web control origin is `http://mycomputer.local:9999`,
then temporarily add `mycomputer.local:9999` to hosts list.

All this should satisfy FoldingAtHome/fah-web-client-bastet/issues/58

**Comment by kbernhagen** [comment]
The option for a direct connect list would still be useful for people that do not want to, or cannot, use the node system.

A better fit for v8.3 might be a Web Control Settings panel with this optional list.

**Comment by jcoffland** [comment]
No longer planning on supporting direct connection other than to the local client.
