### ISSUE TITLE
Web client connection issue appears to hang FAH on overloaded Windows PC

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#65]
I started a GPU WU with the web interface, and it appeared to hang FAH. It was flooding FAH with a loop of connecting and disconnecting the web client (without closing the web client in the browser) on a Windows PC. This prevented FAH from doing much of anything until the web client was closed about 4-5 minutes later (hence the '4 min 26 secs' clock skew message). After closing the web client in the browser, everything started working normally again.

Note: The first group of 'Closing client' messages happened right after starting a GPU WU, with CPU folding running (all but 2 threads of an 8 core HT CPU), and a Firefox web browser with a 100+ tabs open (~61 CPU threads, not using the GPU). So, the PC was overloaded and the web browser probably choked for a moment or lost connection to FAH causing the infinite re-connection loop.

Also, it was the 2 of 3 resource groups that were doing something that were re-connecting.

(only the first 3 lines were shown until the web client was closed 4-5 minutes later)
01:05:21:I1:/RG2:WU5:CORE 100% 
01:05:23:D3:/RG2:Closing client from 127.0.0.1:58222
**_01:05:25:D3:/RG1:Closing client from 127.0.0.1:58221
01:09:04:D3::Closing client from 127.0.0.1:58220_**
01:09:04:D3:/RG1:New client from 127.0.0.1:60065
01:09:04:D3:/RG2:New client from 127.0.0.1:60034
01:09:04:D3:/RG1:New client from 127.0.0.1:60040
01:09:04:D3:/RG2:New client from 127.0.0.1:60049
01:09:04:D3:/RG1:New client from 127.0.0.1:60054
01:09:04:D3:/RG2:New client from 127.0.0.1:60059
01:09:04:D1:/RG2:Remaining CPUs: 0, Remaining GPUs: 0, Active WUs: 1
01:09:04:W :/RG1:WU1:Detected clock skew (4 mins 26 secs), I/O delay, laptop hibernation, other slowdown or clock change noted, adjusting time estimates
01:09:04:D3:/RG1:Closing client from 127.0.0.1:60054
01:09:04:D3:/RG1:Closing client from 127.0.0.1:60040
01:09:04:D3:/RG2:Closing client from 127.0.0.1:60059
...

The web client looked like this while it was hung:
![image](https://user-images.githubusercontent.com/20870053/211177370-23f604db-e220-4fc9-ae11-9236e757607e.png)
Partial log file (let me know if more of the log file is needed): 
[log-20230107-172221.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10367571/log-20230107-172221.txt)

**Comment by jcoffland** [comment]
Clock skew indicates the machine was very heavily loaded.  This is not something that can be fixed in F@H.

```
01:09:04:W :/RG1:WU1:Detected clock skew (4 mins 26 secs), I/O delay, laptop hibernation, other slowdown or 
```
