### ISSUE TITLE
Allow cancelling the Pause All: 'Pause or Finish' dialog 

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#66]
Allow cancelling the Pause All: 'Pause or Finish' dialog, if you decide you really don't want to do either one or it was pressed by accident.
It would be nice if the dialog had a cancel 'X' button in the upper corner, or hitting the 'ESC' key, or clicking on the background of the webpage around the dialog allow it to be cancelled.

**Comment by jcoffland** [comment]
I added a close (X) button to all dialogs.
