### ISSUE TITLE
Update up/download ETA

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#69]
Add updating the ETA time on WU uploads and downloads in the web interface.

The upload 'progress' is updated, but ETA is not being estimated or updated. It currently says '0.00 secs' during the WU upload process:
![image](https://user-images.githubusercontent.com/20870053/211434821-6ec6fde4-54c5-441f-b96a-f170a3578e4f.png)

WU downloads are similar (time not shown):
![image](https://user-images.githubusercontent.com/20870053/211442712-34922732-f4a4-41fa-bf84-d83a0d694605.png)

**Comment by jcoffland** [comment]
This currently only works in Linux.

**Comment by jcoffland** [comment]
This issue is here: https://github.com/FoldingAtHome/fah-client-bastet/issues/130
