### ISSUE TITLE
Feature parity with FAHControl

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-web-client-bastet#70]
This issue is here to track the list of features in the old v7 FAHControl that are not yet complete in v8.

  - <s>Remote access control
     FAHControl lets you set a password to access a remote client.  This is not very secure since the passwords are sent in clear text over the network.  The user is responsible for securing the network so this feature is of questionable merit.  We may replace this by proxying client control via F@H servers.</s>
  - HTTP proxy config. FoldingAtHome/fah-client-bastet/issues/206
    Use of HTTP proxies is much less common today but this is still needed by some.
  - Pause on battery. FoldingAtHome/fah-client-bastet/issues/90
  - WU estimated credit. #84 
  - Ability to pass arguments directly to the cores. https://github.com/FoldingAtHome/fah-client-bastet/issues/207
    It's unclear if supporting this is absolutely necessary.  There is a use case in testing the OpenMMCore.
  - User interface themes. #64

Each of these should also be broken out into a separate issue in either fah-client-bastet or fah-web-client-bastet.

**Comment by kbernhagen** [comment]
Created FoldingAtHome/fah-client-bastet#90

**Comment by kbernhagen** [comment]
See also: [Please display TPF](https://github.com/FoldingAtHome/fah-client-bastet/issues/86)

**Comment by kbernhagen** [comment]
Re PPD, TPF see also: #55

**Comment by Artoria2e5** [comment]
HTTP proxy is required when folding from China. It's actually a proxy software converting some censorship-resistant protocol to HTTP and SOCKS, but the feature is required nonetheless.

**Comment by jcoffland** [comment]
See https://github.com/FoldingAtHome/fah-client-bastet/issues/206

**Comment by jcoffland** [comment]
See #84
