### ISSUE TITLE
Blank web control after adding i.p. to peers box

### ISSUE THREAD

**Issue by bollix47** [FoldingAtHome/fah-web-client-bastet#71]
host windows 11 chrome browser running FAH-Client 8.1.10
peer i.p. 192.168.2.135 linux ubuntu 18.04
after saving settings the web control screen went completely blank as in white with no data or options showing
tried a reboot but white screen  was still there
had to delete client.db which lost the WU
installed 8.1.11 (I did not remove 8.1.10) ....  my identity info did show up (peers blank) but I had to enable the GPU
start folding got me a new WU and it appears to be working well

**Comment by jcoffland** [comment]
It would be useful to see the browser console output (F12).  It sounds like there was an error in the browser code.

**Comment by kbernhagen** [comment]
The blank page is from the client http server denying access.

I’d say this is a bug. The client should return the appropriate http terror code for access denied.

The client added either didn’t have an appropriate http-addresses, or the client had not been restarted.

**Comment by bollix47** [comment]
here is a snippet from the client.db that didn't work properly
„{
  "user": "bollix47",
  "team": 39340,
  "passkey": "xxx",
  "on_idle": false,
  "paused": false,
  "finish": false,
  "cause": "any",
  "cpus": 1,
  "gpus": {
    "gpu:01:00:00": {"enabled": true}
  },
  "peers": ["192.168.2.135"]
} (edited)

**Comment by jcoffland** [comment]
This is caused by Firefox not allowing insecure Websocket connections from an https page.  It should work in Chrome.

**Comment by bollix47** [comment]
This was in chrome .... I don't use Firefox

**Comment by kbernhagen** [comment]
That can’t be it. I don’t think @bollix47 knows how to change the config.xml to allow remote access. It’s bad behavior in web control either way.

**Comment by jcoffland** [comment]
I've fixed this.

**Comment by bollix47** [comment]
fyi my config.xml is setup fine and has been working for years on v7 ... v8 is using the same config.xml

**Comment by kbernhagen** [comment]
Your v7 config will likely not be sufficient for v8 remote access.
