### ISSUE TITLE
Don't start folding if fold-anon, user, team and passkey are all unset

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#73]
First-run

- Picked "Change Settings" in Fold Anon popup
- Changed cpus and Saved, without changing fold anon, user, team, passkey
- Web Control allows click Start Folding
- Nothing happens (folding does not actually start)

Can click Pause Folding

Reloading app page will again show Fold Anon popup, as does a Cancel in Settings

Restarting client causes Fold Anon popup to appear, but the client still thinks it is in unpaused state

**Comment by kbernhagen** [comment]
Web Control should not allow a Start Folding if still "waiting for config".

**Comment by jcoffland** [comment]
We no longer start folding automatically.
