### ISSUE TITLE
Allow individual control over slots similar to FAH Control in v7

### ISSUE THREAD

**Issue by NavicNick** [FoldingAtHome/fah-web-client-bastet#75]
Sometimes I wish to only fold on my CPU/GPU. When one WU finishes on a slot, I pause all the slots, and then I finish the last remaining slot at a later time after I am done with my work. With v8, I cannot resume folding on a specific slot. Both slots will start folding when I press "start folding", and I do not wish for this to happen, as it starts a new WU on a slot I do not want to have folding at the moment.

Similar to FAH Control with v7, I would like to be able to control each slot independently in v8, with the 3 main actions: **start folding**, **pause**, and **finish**, instead of both slots being controlled at the same time with one button.

**Comment by Hou5e** [comment]
The `Resource Groups` functionality does exist in FAH v8, but it's not well documented.
Please see [Issue #52](https://github.com/FoldingAtHome/fah-web-client-bastet/issues/52) for more info on how to enable Resource Groups on your local PC.

It sounds like Resource Groups were intended to be more of a hidden feature. But, unfortunately every advanced user will want this functionality to mimic FAH v7 'slots' until newer WUs are available that can use all the resources you specify to do a single WU.

**Comment by jcoffland** [comment]
There are no "slots" in v8, just WUs.   You can temporarily disable the GPU/CPU resources in the settings.  There is a request to put GPU/CPU control on the main page.

I'm closing this because controlling "slots" is not implemented in the same way as it was in v7.
