### ISSUE TITLE
Work Unit Log stuck on old log after midnight

### ISSUE THREAD

**Issue by jankais3r** [FoldingAtHome/fah-web-client-bastet#79]
Low priority feature request:

I opened the Work Unit Log this morning, and the last entry in the log was from midnight, saying that a new log file will be created due to log rotation rules. Once I refreshed the page, the correct (latest) log file was loaded by the web client, but as an improvement idea I don't see why this couldn't be done dynamically without the need for a page refresh.

**Comment by jcoffland** [comment]
Should be fixed in v8.3.2
