### ISSUE TITLE
Wrong project descriptions

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-web-client-bastet#80]
[hucker75](https://github.com/hucker75) wrote:

According to web control, I'm running (between 5 computers), the following (listed under "projects"):

```
18448 Cancer by Dylan Novack
18449 Cancer by Dylan Novack
18452 Cancer by Dylan Novack
18453 Cancer by Rafal Wiewiora
18717 Cancer by Rafal Wiewiora
```

Yet clicking the links in the "work units" section gives the page https://stats.foldingathome.org/project/[number] showing:

```
18448 Influenza by Dylan Novack
18449 Influenza by Dylan Novack
18452 Cancer by Dylan Novack
18453 Cancer by Dylan Novack
18717 Cancer by Rafal Wiewiora
```

So that's 40% correct, 20% with the wrong researcher, and 40% with the wrong subject.

**Comment by jcoffland** [comment]
Is if fixed now?

**Comment by hucker75** [comment]
I refreshed the page and most of them changed to the correct value.  I now have only one incorrect.  Project 18454 shows Cancer by Rafal Wiewiora on the web interface, but Unspecified by Vincent Voelz on the link.

**Comment by jcoffland** [comment]
Then something is still wrong.  I'm not sure why the the project data is getting mixed up.  I haven't been able to reproduce the problem on my own machines.

**Comment by hucker75** [comment]
Only running two different projects just now, and they're both correct.  Whatever you did improved it a fair bit.

**Comment by hucker75** [comment]
It vastly improved when you made a change.  I've got 7 different projects now, and only 1 is incorrect.

I'm using Windows 11, Chrome, both latest versions.

I've saved and zipped up the html Chrome is displaying.  The 4th project down under Projects (18453) shows Cancer by Rafal, but the link under work units takes me to Cancer by Dylan.

[Zipped html](https://www.dropbox.com/s/hwp6ip8p0ixwox8/Folding%40home%20Client_files.zip?dl=0)

**Comment by jcoffland** [comment]
I've implemented a possible fix.  Please reload your web interface and tell me if it's working correctly now.

**Comment by kbernhagen** [comment]
The latest fix today seems to be working for me on macOS (Brave, Chrome) and Windows (Edge).

**Comment by hucker75** [comment]
All 5 projects on 7 GPUs are now correct, thankyou.
