### ISSUE TITLE
The new drivers section on the GPU settings shows not supported

### ISSUE THREAD

**Issue by Josh65-2201** [FoldingAtHome/fah-web-client-bastet#85]
![image](https://user-images.githubusercontent.com/26977075/221416981-05d6a85b-9054-4407-93cf-1639b2516a65.png)

When running a work unit it uses the GPU CUDA cores fine but in the settings interface say nothing is supported.

**Comment by jcoffland** [comment]
This is because the web interface is slightly ahead of the backend software.  The next release will fix this.

**Comment by Josh-65** [comment]
Alright cool. Will the backend auto update or show a notification for updates?

**Comment by jcoffland** [comment]
Neither, but we should probably add an announcement via the web interface when a new version is available.

    https://github.com/FoldingAtHome/fah-web-client-bastet/issues/86

**Comment by jcoffland** [comment]
Fixed.
