### ISSUE TITLE
Allow creation of certificates at predetermined Work Unit values

### ISSUE THREAD

**Issue by TessellateDataScience** [FoldingAtHome/fah-web-client-bastet#87]
Wondering if this could be an effective way to market Folding@home in a more restrained way? People have certificates in the background of their Zoom meetings. I know they can currently be created, but maybe this would feature request would allow more 'nice' value (such as 1000, 10000, etc) that would feel more normal (than odd values such as 953, for example).

**Comment by TessellateDataScience** [comment]
I'm happy to attempt this task. Any idea where I should look to get the username/team data?

**Comment by jcoffland** [comment]
This is an issue for the stats system.  Please report here: https://github.com/FoldingAtHome/fah-issues/issues

**Comment by TessellateDataScience** [comment]
Thanks Joseph, I've requested it there.
