### ISSUE TITLE
When using Dark Mode, the 'Projects' section has very bad contrast

### ISSUE THREAD

**Issue by cameronlyman** [FoldingAtHome/fah-web-client-bastet#91]
When using Dark Mode, the 'Projects' section has bad contrast making it very hard to read. This will be an issue for those with vision problems as according to the Mozilla Accessibility guidelines.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast

I suggest removing the "background" attribute in the .project CSS.

![image](https://user-images.githubusercontent.com/20762251/226689054-bbdd1ebc-6699-4959-850c-b0e54a16f505.png)
![image](https://user-images.githubusercontent.com/20762251/226689833-23994b5d-7c1d-48f6-aca4-5e7eac9cc7b6.png)

**Comment by jcoffland** [comment]
fixed
