### ISSUE TITLE
Strange light mode bar exists when using Dark mode

### ISSUE THREAD

**Issue by cameronlyman** [FoldingAtHome/fah-web-client-bastet#92]
Likely related to [issue #91](https://github.com/FoldingAtHome/fah-web-client-bastet/issues/91). A bar now appears on the left side of the screen after issue #91 was fixed.

Browser used is Mozilla 111.0.1 (64-bit).

![image](https://user-images.githubusercontent.com/20762251/226797662-bbdc348d-8107-4a27-876e-035949cd0b8a.png)

**Comment by kbernhagen** [comment]
Are you using macOS?

I see the same, but it goes away if I change show scrollbars to when scrolling via System Preferences.

Not saying it isn’t fixable in css. I’ve never seen any other site do this.

**Comment by kbernhagen** [comment]
Seems to partly be `body { padding-left }`

**Comment by jcoffland** [comment]
I don't see it in FF.

**Comment by cameronlyman** [comment]
I use Windows 10 22H2.

**Comment by cameronlyman** [comment]
> Are you using macOS?
> 
> I see the same, but it goes away if I change show scrollbars to when scrolling via System Preferences.
> 
> Not saying it isn’t fixable in css. I’ve never seen any other site do this.
> 
> Edit: see same thing in Safari, Chrome, Edge, Brave.

I use Windows 10 22H2

**Comment by jcoffland** [comment]
Should be fixed now.

**Comment by cameronlyman** [comment]
I still see the issue even after updating to 8.1.17.

**Comment by jcoffland** [comment]
You might need to hard refresh your browser.

**Comment by cameronlyman** [comment]
It went away. Thank you for fixing this
