### ISSUE TITLE
Still getting problems with being unable to turn off CPU work.

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-web-client-bastet#93]
Could we just have a disable CPU option?  I have a PC with 2 GPUs, I removed one.  Now the web interface has the slider for the CPU allowing 2 to 24 cores.  Setting it to 2, it's downloading 1-core CPU work.

![image](https://user-images.githubusercontent.com/66015018/228163029-a8908088-5498-48b8-99f1-8974039e1f5e.png)

**Comment by jcoffland** [comment]
This should be fixed.  Please confirm.

**Comment by hucker75** [comment]
Confirmed, thankyou.
