### ISSUE TITLE
Web client not showing when a remote computer is crashed/off.

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-web-client-bastet#95]
Overnight a remote computer I monitor from the web client on this machine had crashed.  Yet it still shows "running" with the spinning green arrows.  I even went and shut down the offending machine, and it still shows running.  It would be nice to be informed when a computer has failed.  I only knew about it because it also runs Boinc, and that showed a disconnected symbol.

**Comment by jcoffland** [comment]
Can you confirm that this is now fixed?

**Comment by jcoffland** [comment]
Apparently the timeout could be as long as 10mins.  We probably need a keep alive message.

**Comment by jcoffland** [comment]
Should be fixed in v8.1.18.  It should timeout with in 30s.

**Comment by kbernhagen** [comment]
While messing with my utilities, I was seeing an error that seemed to indicate that the client might never actually send a websocket close data frame.

**Comment by kbernhagen** [comment]
I was thinking maybe the websocket object was getting deallocated before pending data gets sent because libevent would send later.

**Comment by kbernhagen** [comment]
Maybe I'm wrong about close.
My python utility will immediately print this when client exits normally:
```
no close frame received or sent
```

**Comment by kbernhagen** [comment]
Nevermind. It seems to be a standard ConnectionClosed exception when the socket is closed during await recv().
