### ISSUE TITLE
WebControl's settings and log pages are blank

### ISSUE THREAD

**Issue by iiaiiappa** [FoldingAtHome/fah-web-client-bastet#98]
v8.1.17

https://app.foldingathome.org/settings
https://app.foldingathome.org/log

is blank page, even after cleaning the browser cache.
Used latest versions of Edge, Chrome, Firefox.

![image](https://user-images.githubusercontent.com/403553/232345181-90dee81c-7c3e-4e52-9b85-3c78f9032dc8.png)

![image](https://user-images.githubusercontent.com/403553/232345165-e99d4ceb-2006-4f73-97fe-5f38a4147d80.png)

**Comment by kbernhagen** [comment]
Yes, thanks for your report.

There are three workarounds:

- use a local web control https://foldingforum.org/viewtopic.php?t=39131

- do not have any peers

- manually add the peer number to the url (replace /settings with /0/settings)

**Comment by jcoffland** [comment]
Should be working now.

**Comment by kbernhagen** [comment]
Works for me.

**Comment by iiaiiappa** [comment]
to add more infomation for reference, I meant the peer's setting icons at the main web control page show blank pages.
![image](https://user-images.githubusercontent.com/403553/232603249-7eedc1ff-20d1-429c-889d-4c9b4b753e8e.png)
